config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :artists
  # resources :artists do
  #   resources :albums
  # end
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :artist
  has_many :songs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :albums
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :album
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end
  def show
    @artist = Artist.find(params[:id])
    # @albums = Artist.find(params[:id]).albums[0].name
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/index.html.erb
<table border="1">
  <tr>
    <th>Name</th>
    <th>Imagen</th>
  </tr>
  <% @artists.each do |artist| %>
  <tr>
      <td><%= link_to artist.name, artist_path(artist) %></td>
      <td><img src="<%= artist.image_url %>" alt="<%= artist.name %>" width="200"></td>
  <% end %>
  </tr>
</table>

app/views/artists/show.html.erb
<h1><%= @artist.name %></h1>
<%= link_to 'Regresar', artists_path() %>
<br>
<h1>Albumes</h1>
<% if @artist.albums.count == 0 %>
  <h1>No Tiene Albunes Creados</h1>
<% else %>
  <% @artist.albums.each do |album| %>
  <h2><%= album.name %></h2>
  <h3><%= album.released_at  %></h3>
  <img src="<%= album.image_url %>" alt="<%= album.name %>" width="200">
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicaYMasMusica</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>